/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verifica status da API
     * @description Retorna o status da aplicação e a conexão com o banco de dados. Use este endpoint para monitoramento e health checks de infraestrutura.
     */
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    HealthApiResponseDto: {
      /**
       * @description Indica se a requisicao foi bem-sucedida
       * @constant
       */
      success: true;
      /** @description Dados de saude da aplicacao */
      data: {
        /**
         * @description Status geral da aplicacao
         * @enum {string}
         */
        status: 'ok' | 'error';
        /**
         * @description Status da conexao com o banco de dados
         * @enum {string}
         */
        database: 'connected' | 'disconnected';
        /** @description Data/hora da verificacao (ISO 8601) */
        timestamp?: string;
        /** @description Ambiente de execucao */
        environment?: string;
        /** @description Mensagem de erro (apenas quando status = error) */
        error?: string;
      };
      /** @description Mensagem descritiva (opcional) */
      message?: string;
    };
    ApiErrorResponseDto: {
      /**
       * @description Indica que houve erro
       * @constant
       */
      success: false;
      /** @description Codigo HTTP do erro */
      statusCode: number;
      /** @description Mensagem de erro */
      message: string;
      /** @description Detalhes do erro (validacao, etc.) */
      errors?: string[];
      /** @description Timestamp do erro */
      timestamp: string;
      /** @description Caminho da requisicao */
      path?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Sistema operacional */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthApiResponseDto'];
        };
      };
      /** @description Sistema com falha (banco desconectado) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApiErrorResponseDto'];
        };
      };
    };
  };
}
